/** Location of the forward-only SQL migrations (generated by drizzle-kit, never edited). */
import { fileURLToPath } from "node:url";

// Two levels below the package root in both src/db and dist/db.
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../../src/db/migrations", import.meta.url));
